### PR TITLE
Add raycaster attribute to cursor and text primitive

### PR DESCRIPTION
**Pull request by SebastianMuszynski**
1. Would be great to be able to use `raycaster` attribute.

Ref: https://aframe.io/docs/0.5.0/components/cursor.html#configuring-the-cursor-through-the-raycaster-component

2. Added missing [text](https://aframe.io/docs/0.5.0/primitives/a-text.html) primitive.

_Please ignore the previous PR (already closed) as I have messed something up with the commits._

### CODE REVIEW

**Comment by halfzebra** [comment]
@SebastianMuszynski thanks for the PR!

Merged 👍

**Comment by SebastianMuszynski** [comment]
@halfzebra Awesome! Could you bump the package version? Elm is still installing the package without those changes (unless I'm doing something wrong?).

**Comment by halfzebra** [comment]
@SebastianMuszynski I have [bumped the version](http://package.elm-lang.org/packages/halfzebra/elm-aframe/latest) of the package so you could use the new stuff! 🎉

**Comment by SebastianMuszynski** [comment]
Amazing, thanks! 😎

**Pull request merged**
